# Generated by Django 4.0.6 on 2022-07-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j_orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
