# Generated by Django 4.0.6 on 2022-07-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('j_orm', '0002_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='j_orm.blog')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('j_orm.blog',),
        ),
    ]
