# Generated by Django 4.0.6 on 2022-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm1', '0005_remove_order_tag_products_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discreption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
