# Generated by Django 4.0.6 on 2022-07-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm1', '0009_feedback_userregister_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
